name: Python less than 3.6
on:
  push:
   branches:
    - master
  pull_request:
    branches:
     - master

jobs:
  python3-4:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.4']
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Tox
        run: |
          python -m pip install --upgrade pip
          pip install -Iv pyyaml==5.2b1
          pip install tox
      - name: Install Make
        run: sudo apt install build-essential
      - name: Run Tests for Python 3.4
        env:
          TOXENV: py34
        run: make test
  
  python3-5:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.5']
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Install Make
        run: sudo apt install build-essential
      - name: Run Tests for Python 3.5
        env:
          TOXENV: py35
        run: make test