name: tox
on:
  push:
   branches:
    - master
  pull_request:
    branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.4', '3.5', '3.6' , '3.7' ]
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Tox and Github Actions Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Install Make
        run: sudo apt install build-essentials
      - name: Run Tests with Tox
        run: make test